version: '3.0'

services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '9080:8080'
      - '7077:7077'
  #       volumes:
  #           - ../build/libs/spark-tute-0.0.1-SNAPSHOT.jar:/opt/bitnami/spark/jars/spark-tute-0.0.1-SNAPSHOT.jar
  spark-worker:
    image: docker.io/bitnami/spark:3.5
    deploy:
      replicas: 5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
#        volumes:
#            - ../build/libs/spark-tute-0.0.1-SNAPSHOT.jar:/opt/bitnami/spark/jars/spark-tute-0.0.1-SNAPSHOT.jar

